# Generated by Django 5.2.6 on 2025-09-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='dedline',
            new_name='deadline',
        ),
    ]
